set(TTP_APE_SDK_ARCHIVE "" CACHE FILEPATH "Optional local copy of the pinned official SDK ZIP")
set(mac_source "${CMAKE_CURRENT_BINARY_DIR}/downloads/MAC_1327_SDK")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/cmake/prepare_mac.py")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/cmake/prepare_mac.py"
  "${mac_source}" "${TTP_APE_SDK_ARCHIVE}" COMMAND_ERROR_IS_FATAL ANY)
set(BUILD_SHARED OFF CACHE BOOL "Static MAC core" FORCE)
set(BUILD_UTIL OFF CACHE BOOL "No SDK utility" FORCE)
add_subdirectory("${mac_source}" "${CMAKE_CURRENT_BINARY_DIR}/mac" EXCLUDE_FROM_ALL)
get_target_property(mac_sources objects SOURCES)
list(FILTER mac_sources EXCLUDE REGEX "MACDll/MACDll\\.cpp$")
set_property(TARGET objects PROPERTY SOURCES "${mac_sources}")
foreach(target shared objects)
  set_property(TARGET ${target} PROPERTY COMPILE_OPTIONS /W3 /EHsc /utf-8 /Os /Gy /Gw /GF /arch:SSE2 /Zc:threadSafeInit-)
  set_property(TARGET ${target} PROPERTY COMPILE_DEFINITIONS PLATFORM_WINDOWS_XP _CRT_SECURE_NO_WARNINGS)
endforeach()
